lnd-1:
  rtl:
    enable: false
  configurationFile:
    lnd.conf: |-
      bitcoin.active=1
      alias=bolt.fun.k8s.demo
      bitcoin.mainnet=1
      bitcoin.testnet=0
      debuglevel=info
      bitcoin.node=neutrino
      rpclisten=0.0.0.0:10009
      tlsextraip=0.0.0.0
      neutrino.addpeer=btcd-mainnet.lightning.computer
      neutrino.addpeer=mainnet1-btcd.zaphq.io
      neutrino.addpeer=mainnet2-btcd.zaphq.io
      neutrino.addpeer=mainnet3-btcd.zaphq.io
      neutrino.addpeer=mainnet4-btcd.zaphq.io
      neutrino.feeurl=https://nodes.lightning.computer/fees/v1/btc-fee-estimates.json
      protocol.wumbo-channels=1
      prometheus.enable=false
      prometheus.listen=0.0.0.0:8989
      wallet-unlock-password-file=/passwords/wallet_password
  autoUnlock: true
  autoUnlockPassword: boltfunbtc
  resources:
    requests:
      memory: 300Mi
      cpu: 800m
    limits:
      memory: 2Gi
      cpu: 1000m
cln-1:
  image:
    tag: 0.12.3
  args:
    - '--disable-plugin=bcli'
    - '--log-level=debug'
    - '--addr=0.0.0.0:9735'
    - '--plugin=/opt/lightningd/plugins/trustedcoin'
    - '--grpc-port=9737'
    - '--experimental-offers'
  ingress:
    enabled: false
  resources:
    requests:
      memory: 128Mi
      cpu: 100m
    limits:
      memory: 512Mi
      cpu: 200m